### ISSUE TITLE
feature: Avoid duplicate rendering when using tmux backend

### ISSUE THREAD

**Issue by Welkin-Y** [folke/sidekick.nvim#36]
### Did you check the docs?

- [x] I have read all the sidekick.nvim docs

### Is your feature request related to a problem? Please describe.

<img width="1172" height="138" alt="Image" src="https://github.com/user-attachments/assets/33565ece-107b-42bd-a78c-d94f661fe236" />
When using with the tmux backend, the buffer gets rendered inside nvim according to my`.tmux.conf`.

## Expected Behavior

A simplest tmux panel without any plugins

## Possible Solutions

I wonder if it is possible to make the embedded tmux panel using another user specified config file.

**Comment by folke** [comment]
Fixed!

A custom config gets passed that includes the user's config, and just disables the status bar.

**Comment by Welkin-Y** [comment]
Hi folke, thanks for the rapid fix. 
I just tested it on my end and it seems the duplicate rendering issue still remain on my side. 
However, your solutions inspired me.  I modified a bit and it nicely worked. Instead off appending `set -g status off` to configs, adding  a `set-option status off` flag to `tmux` command can solve my issue.

I have created a PR https://github.com/folke/sidekick.nvim/pull/42

I am not sure if it was because of some behaviour due to tmux plugins, and here is my tmux config.
<details><summary> tmux config</summary>

```tmux
set -g mouse on
set -g default-terminal "tmux-256color"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @plugin 'alexwforsythe/tmux-which-key'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'


# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha" # latte, frappe, macchiato, or mocha
set -g @catppuccin_window_status_style "rounded" # basic, rounded, slanted, custom, or none

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"


run '~/.tmux/plugins/tpm/tpm'
```

</details>
